[stangastaden]
title = "Stångåstaden Lägenheter"
url = "https://www.stangastaden.se/sokledigt/bostad?actionId=&oboTyper%5B%5D=A3&oboTyper%5B%5D=A4&oboTyper%5B%5D=A5&oboTyper%5B%5D=A6&oboTyper%5B%5D=A7&ytaMin=50&ytaMax=300&hyraMax=25000"
entrySelector = ".search-list-item"
titleSelector = "a .list-item-header"
linkSelector = "a"
