[stangastaden]
title = "Stångåstaden Lägenheter"
url = "https://www.stangastaden.se/sokledigt/bostad?actionId=&oboTyper%5B%5D=A3&oboTyper%5B%5D=A4&oboTyper%5B%5D=A5&oboTyper%5B%5D=A6&oboTyper%5B%5D=A7&ytaMin=50&ytaMax=300&hyraMax=25000"
entrySelector = ".search-list-item"
titleSelector = "a .list-item-header"
linkSelector = "a"
#contentSelector = [".search-display-info", ".search-left-column img", ".search-right-column"]
contentSelector = ".search-list-item-anchor"
waitUntil = "networkidle"

[happyride]
title = "Happyride annonser"
url = ["https://happyride.se/annonser/list.php?search=trek+mondraker&category=1&county=&creator=&type=1", "https://happyride.se/annonser/list.php?search=trek+mondraker&category=2&county=&creator=&type=1", "https://happyride.se/annonser/list.php?search=xx1+hope+etap+aliante+power2max&category=3&county=&creator=&type=1&year=0&price_from=&price_to="]
entrySelector = ".sales-table tr"
filters = ["Kategori"]
titleSelector = ".col-2 h4"
linkSelector = ".col-1 a"
waitUntil = "load"
